Update authentication to use PAK
joerg65/pytedee pull request #6
Opened 2021-11-02 08:36 UTC by klucyszy

Changes:
- API version upgrade from 1.15 to 1.22
- authentication method changed from ROPC to PAK
- avoid null reference errors when assigning lockProperties values

2021-11-02 08:47 UTC, NimlothPL commented
Are U sure of this url:
api_url_base = "https://t01-nofo-api.azurewebsites.net/api/v1.22/"
?

Based on documentation it should be https://api.tedee.com/v1.22/

2021-11-02 10:07 UTC, klucyszy commented
@NimlothPL the link has been updated.

2021-11-05 08:59 UTC, NimlothPL commented
Side note - I tested API with Personal Key and it works - nice :)
What should be documented (maybe in readme), minimal scope needed for this integration to work.
Also validTo is not well documented - exact format need to be used or also short one will work like "2025-11-05"

I tested with (manual API queries):
{
  "name": "Test",
  "validTo": "2021-11-05T15:33:29.054Z",
  "scopes": [
    "Device.Read",
    "Lock.Operate"
  ]
}

2021-11-15 07:38 UTC, klucyszy commented
Hi, thanks for testing, and glad to hear that PAK is working fine.

I've added commit with an updated Readme file. Now it contains the minimum scopes required to use the integration. Regarding the date is the date format compliant with [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). We will precise the Tedee documentation in the next iteration too.

Best regards
Kamil

2022-01-15 12:09 UTC, joerg65 requested changes

2022-01-15 12:09 UTC, joerg65 commented on pytedee/pytedee/TedeeClient.py
> +                        lock_batteryLevel = self.assign_null_or_lock_state(lockProperties)
Must be changed to:
```lock_batteryLevel = self.assign_null_or_lock_batteryLevel(lockProperties)```

2022-01-15 12:09 UTC, joerg65 commented on pytedee/pytedee/TedeeClient.py
> -    def update(self, id):
For periodically update of the home assistant custom component, function update need to be there:
```
def update(self, id)
  self.get_state()
  return self.get_battery(id)
```

2022-02-02 22:08 UTC, klucyszy commented
@joerg65 thanks for review. I've resolved your comments. please check ;)

2022-02-03 12:05 UTC, joerg65 approved these changes

2022-02-03 12:06 UTC, merged